GoogleForms/GoogleForms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("forms.urls"))
]

GoogleForms/forms/urls.py
from django.urls import path
from . import views

app_name = "forms"

urlpatterns = [
    path("",views.home, name= "home",),
    path("create", views.create, name= "create"),
    path("forms/<str:pk>/edit", views.update_form, name="update_form"),
]

GoogleForms/forms/models.py
from django.db import models

# Create your models here.

GoogleForms/forms/admin.py
from django.contrib import admin

# Register your models here.

GoogleForms/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "forms"

GoogleForms/forms/tests.py
from django.test import TestCase

# Create your tests here.

GoogleForms/forms/utils.py
import pymongo
from django.utils import timezone 

from bson import ObjectId

client = pymongo.MongoClient("mongodb://localhost:27017/")
db = client["GoogleForms"]
col = db["GoogleForms"]

class Form:
    def create(self):
        obj = col.insert_one({
            "created":timezone.now()
        })  
        return str(obj.inserted_id)

    def find(self,pk):
        query = {
            "_id":ObjectId(pk)
        }
        obj = col.find(query).next() #cursor object

        return obj

GoogleForms/forms/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse_lazy
from django.http import Http404
from .utils import Form
    


# Create your views here.
form = Form()

def get_random_uuid():
    return "my_simple_uuid"

def home(request):
    return render(request, "home.html")

def create(request):
    pk = form.create()
    return HttpResponseRedirect(reverse_lazy("forms:update_form",args=[pk]))

def update_form(request,pk):

    if request.method == "POST":
        data = request.POST
        print(data)
        print(data.getlist("InputText"))

    try:
        #Genrate Some Error
        form_data = form.find(pk)
        return render(request,"update_form.html",{
            "pk":pk,
            "form":form_data
        })
    except Exception as e:
        print(e)
        #return 404
        raise Http404("Form not Found")

GoogleForms/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body>
    {% block content %}{% endblock content %}
</body>

{% block script %}{% endblock script %}

</html>

GoogleForms/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>FormsBase</h1>
    <a href="{% url "forms:create" %}"><button>Create Form</button></a>
</body>
</html>

GoogleForms/templates/update_form.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'forms:update_form' pk %}" method="post" id='questionForm'>
    {% csrf_token %}
    <Button type='submit'>Save</Button>

    <div class="card" id='form-description'>
        <div class="card-header">
            Title and Description
        </div>
        <div class="card-body">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="title" placeholder="title" name='title'>
                <label for="title">Form Title</label>
            </div>
            <div class="form-floating">
                <textarea class="form-control" placeholder="Description" id="description"
                    name='description'></textarea>
                <label for="description">Form Description</label>
            </div>
        </div>
        <button type='button' id='addQuestion'>Add Question</button>
    </div>
{% endblock content %}